"""Data Passport: Ed25519-signed summary of a verified dataset.

content hash = sha256(canonical JSON of [[episode_id, sha256(canonical JSON of episode)], ...])
over the accepted split (PASS episodes + REPAIR episodes in repaired form).
The signature covers the canonical JSON of the passport without its "signature" field.
"""
from __future__ import annotations

import base64
import json
import platform
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

import cryptography
import matplotlib
import numpy as np
import z3
from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey, Ed25519PublicKey

from engine.verifier import ENGINE_VERSION
from kernel.rulebook import RULEBOOK_VERSION, rulebook_hash
from util import (ACCEPTED_FILE, HELDOUT_FILE, KEYS_DIR, PASSPORT_FILE, RESULTS_DIR, ROOT, canonical_json,
                  read_jsonl, sha256_hex, write_json)

PRIV = KEYS_DIR / "axiomality_demo_ed25519.pem"
PUB = KEYS_DIR / "axiomality_demo_ed25519.pub.pem"
KEY_README = """# DEMO KEY - DO NOT USE IN PRODUCTION

`axiomality_demo_ed25519.pem` is an **unencrypted demo private key** generated by
`passport/passport.py` for the AXIOMALITY prototype. It lives in plain text next to
the code, so anyone with this folder can forge passports signed by it.

A production deployment must keep the signing key in an HSM/KMS, publish the
public key through a trusted channel, and support key rotation/revocation.
Only `axiomality_demo_ed25519.pub.pem` is needed to verify a passport.
"""


def ensure_keys() -> None:
    KEYS_DIR.mkdir(exist_ok=True)
    (KEYS_DIR / "README.md").write_text(KEY_README)
    if PRIV.exists() and PUB.exists():
        return
    sk = Ed25519PrivateKey.generate()
    PRIV.write_bytes(sk.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                                      serialization.NoEncryption()))
    PUB.write_bytes(sk.public_key().public_bytes(serialization.Encoding.PEM,
                                                 serialization.PublicFormat.SubjectPublicKeyInfo))


def load_public(path: Path = PUB) -> Ed25519PublicKey:
    return serialization.load_pem_public_key(path.read_bytes())


def key_id(pk: Ed25519PublicKey) -> str:
    raw = pk.public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
    return "ed25519:" + sha256_hex(raw)[:16]


def content_manifest(episodes: list[dict]) -> tuple[str, list]:
    manifest = sorted([e["episode_id"], sha256_hex(canonical_json(e))] for e in episodes)
    return "sha256:" + sha256_hex(canonical_json(manifest)), manifest


def issue() -> dict:
    ensure_keys()
    sk = serialization.load_pem_private_key(PRIV.read_bytes(), password=None)
    accepted = read_jsonl(ACCEPTED_FILE)
    submitted = read_jsonl(HELDOUT_FILE)
    verdicts = json.loads((RESULTS_DIR / "engine_verdicts.json").read_text())
    root, manifest = content_manifest(accepted)
    counts = Counter(v["verdict"] for v in verdicts)
    by_rule, by_family = Counter(), Counter()
    for v in verdicts:
        rules = {f["rule"] for f in v["findings"]} | {r["rule"] for r in v["repairs"]}
        by_rule.update(rules)
        by_family.update({r.rsplit("-", 1)[0] for r in rules})
    n_syn = sum(bool(e["meta"].get("synthetic")) for e in accepted)
    passport = {
        "passport_version": "ax-passport/0.1",
        "dataset_id": "AX-DEMO-109",
        "title": "SYNTHETIC pick-and-place episodes derived from sample 109 (demo)",
        "issuer": "AXIOMALITY prototype engine (demo key - not a production issuer)",
        "issued_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "content": {"accepted_split_file": str(ACCEPTED_FILE.relative_to(ROOT)), "episodes": len(accepted),
                    "frames": sum(len(e["frames"]["t"]) for e in accepted),
                    "content_hash": root, "hash_method": "sha256 over canonical JSON of sorted [episode_id, sha256(canonical episode JSON)]",
                    "episode_hashes": manifest},
        "rulebook": {"version": RULEBOOK_VERSION, "hash": rulebook_hash()},
        "verdict_counts": {"submitted": len(submitted), **{k: counts.get(k, 0) for k in ("PASS", "REPAIR", "REJECT", "UNKNOWN")}},
        "findings_summary": {"episodes_by_rule_family": dict(sorted(by_family.items())),
                             "episodes_by_rule": dict(sorted(by_rule.items()))},
        "real_synthetic": {"real": len(accepted) - n_syn, "synthetic": n_syn,
                           "real_ratio": (len(accepted) - n_syn) / len(accepted) if accepted else None},
        "provenance": {"seed_sample": {"folder": "pointclouds", "filename": "109.ply",
                                       "sha256": sha256_hex((ROOT / "data" / "seed_sample_109.json").read_bytes())},
                       "generator": sorted({e["meta"]["generator"] for e in accepted}),
                       "robot_ids": sorted({e["meta"]["robot_id"] for e in accepted}),
                       "calibration_hashes": sorted({e["meta"]["calibration_hash"] for e in accepted}),
                       "consent_ids": f"{len({e['meta']['consent_id'] for e in accepted})} distinct (synthetic, no human subjects)"},
        "checks": {"engine": ENGINE_VERSION, "rule_families": sorted({r.rsplit('-', 1)[0] for r in by_rule} | {
            "R-PROV", "R-TIME", "R-QTY", "R-TYPE", "R-JNT", "R-KIN", "R-GRIP", "R-CONT", "R-PERM", "R-SUP", "R-SPAT",
            "R-PHASE", "R-TASK"}),
                   "tools": {"python": platform.python_version(), "z3-solver": z3.get_version_string(),
                             "numpy": np.__version__, "cryptography": cryptography.__version__,
                             "matplotlib": matplotlib.__version__}},
        "limitations": ["All episodes are synthetic; no real robot data.",
                        "Not a safety certification.",
                        "Physics checks are kinematic (no force/torque data)."],
    }
    pk = sk.public_key()
    sig = sk.sign(canonical_json(passport))
    passport["signature"] = {"alg": "Ed25519", "key_id": key_id(pk), "signed": "canonical JSON of passport without 'signature'",
                             "public_key_pem": pk.public_bytes(serialization.Encoding.PEM,
                                                               serialization.PublicFormat.SubjectPublicKeyInfo).decode(),
                             "value_b64": base64.b64encode(sig).decode()}
    write_json(PASSPORT_FILE, passport)
    print(f"[passport] {PASSPORT_FILE.relative_to(ROOT)}: {len(accepted)} accepted episodes, content {root[:23]}..., "
          f"key {key_id(pk)}")
    return passport


def verify(passport_path: Path = PASSPORT_FILE, pubkey_path: Path = PUB, data_path: Path | None = None) -> tuple[bool, list[str]]:
    """Offline verification: signature (trusted public key file) + recomputed content hash."""
    msgs, ok = [], True
    passport = json.loads(Path(passport_path).read_text())
    sig = passport.pop("signature", None)
    if sig is None:
        return False, ["FAIL no signature"]
    pk = load_public(Path(pubkey_path))
    if sig.get("key_id") != key_id(pk):
        ok = False
        msgs.append(f"FAIL key id {sig.get('key_id')} does not match trusted public key {key_id(pk)}")
    try:
        pk.verify(base64.b64decode(sig["value_b64"]), canonical_json(passport))
        msgs.append(f"OK   signature valid (Ed25519, {key_id(pk)})")
    except InvalidSignature:
        ok = False
        msgs.append("FAIL signature INVALID - passport fields were modified after signing")
    data_path = Path(data_path) if data_path else ROOT / passport["content"]["accepted_split_file"]
    eps = read_jsonl(data_path)
    root, manifest = content_manifest(eps)
    if root == passport["content"]["content_hash"]:
        msgs.append(f"OK   content hash matches ({len(eps)} episodes, {root[:23]}...)")
    else:
        ok = False
        signed = dict(map(tuple, passport["content"]["episode_hashes"]))
        now = dict(map(tuple, manifest))
        diff = sorted(k for k in set(signed) | set(now) if signed.get(k) != now.get(k))
        msgs.append(f"FAIL content hash mismatch: {root[:23]}... != signed {passport['content']['content_hash'][:23]}...; "
                    f"changed episodes: {', '.join(diff[:5])}")
    rb = passport["rulebook"]
    if rb.get("overrides") is not None:  # v2 tolerance profile: recompute from the recorded overrides
        from kernel.profiles import rulebook_v2_hash
        expect = rulebook_v2_hash(rb["overrides"])
    else:
        expect = rulebook_hash()
    if rb["hash"] != expect:
        msgs.append("WARN rulebook in this checkout differs from the one the passport was issued under")
    if "real_mode" in passport:
        from engine.real_mode import catalogue_hash
        if passport["real_mode"]["catalogue_hash"] != catalogue_hash():
            msgs.append("WARN real-mode check catalogue in this checkout differs from the one used for the passport")
    return ok, msgs


def issue_generic(out_path: Path, accepted: list[dict], accepted_file: Path, body: dict) -> dict:
    """Sign a passport for any accepted split. ``body`` supplies dataset_id, title, rulebook,
    verdict_counts, findings_summary, real_synthetic, provenance, checks, known_limitations, ...
    The content hash is computed here from ``accepted`` (which must equal the file's content)."""
    ensure_keys()
    sk = serialization.load_pem_private_key(PRIV.read_bytes(), password=None)
    root, manifest = content_manifest(accepted)
    passport = {"passport_version": "ax-passport/0.2",
                "issuer": "AXIOMALITY prototype engine (demo key - not a production issuer)",
                "issued_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(), **body}
    passport["content"] = {"accepted_split_file": str(accepted_file.relative_to(ROOT)), "episodes": len(accepted),
                           "frames": sum(len(next(iter(e["frames"].values()))) for e in accepted),
                           "content_hash": root,
                           "hash_method": "sha256 over canonical JSON of sorted [episode_id, sha256(canonical episode JSON)]",
                           "episode_hashes": manifest}
    passport["checks"] = dict(passport.get("checks", {}), tools={
        "python": platform.python_version(), "z3-solver": z3.get_version_string(), "numpy": np.__version__,
        "cryptography": cryptography.__version__, "matplotlib": matplotlib.__version__})
    pk = sk.public_key()
    sig = sk.sign(canonical_json(passport))
    passport["signature"] = {"alg": "Ed25519", "key_id": key_id(pk), "signed": "canonical JSON of passport without 'signature'",
                             "public_key_pem": pk.public_bytes(serialization.Encoding.PEM,
                                                               serialization.PublicFormat.SubjectPublicKeyInfo).decode(),
                             "value_b64": base64.b64encode(sig).decode()}
    write_json(out_path, passport)
    return passport


if __name__ == "__main__":
    sys.exit(0 if issue() else 1)
